# -*- coding: utf-8 -*-
"""Fake News Detector

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cozmNpbkx7Sk5s_PW_R7yw8DawNudRGE
"""

pip install numpy pandas sklearn

pip install colabcode

import numpy as np
import pandas as pd
import itertools
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

#Read the data
df= pd.read_csv('/content/drive/MyDrive/news.zip')

#Get the shape and head of the data
df.shape
df.head()

#use data flair to get the respective labels
labels=df.label
labels.head()

#use dataflair to spilt the data set
x_train,x_test,y_train,y_test=train_test_split(df['text'], labels, test_size=0.2, random_state=7)

#Initialize a TfidfVectorizer
tfidf_vectorizer=TfidfVectorizer(stop_words='english', max_df=0.7)

#Fit the training and test data
tfidf_train=tfidf_vectorizer.fit_transform(x_train) 
tfidf_test=tfidf_vectorizer.transform(x_test)

#Initialize a PassiveAggressiveClassifier
pac=PassiveAggressiveClassifier(max_iter=50)
pac.fit(tfidf_train,y_train)

#Predict based the test set and calculate and output accuracy
y_pred=pac.predict(tfidf_test)
score=accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

#Build confusion matrix
confusion_matrix(y_test,y_pred, labels=['FAKE','REAL'])